version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  system_packages: true
  sys_path:
    - ${{ project_slug }}/src
  install:
    - requirements: docs/requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .
      extra_requirements:
        - src

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true
